<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Confluent Kafka -->
    <PackageVersion Include="Confluent.SchemaRegistry" Version="2.11.0" />
    <PackageVersion Include="Confluent.SchemaRegistry.Serdes.Json" Version="2.11.0" />
    <PackageVersion Include="Confluent.SchemaRegistry.Serdes.Avro" Version="2.11.0" />

    <!-- ASP.NET Core -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.7" />

    <!-- Visual Studio Tools -->
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />

    <!-- JSON -->
    <PackageVersion Include="Newtonsoft.Json.Schema" Version="4.0.1" />

    <!-- Testing -->
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="Testcontainers" Version="4.6.0" />

    <!-- OpenTelemetry -->
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
  </ItemGroup>
</Project>