<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ec506465-ecb5-4b60-99ed-8676f8a09498</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\KafkaConsumerApp\KafkaConsumerApp.csproj" />
    <ProjectReference Include="..\src\KafkaProducer.WebApp\KafkaProducer.WebApp.csproj" />
  </ItemGroup>

</Project>
